language: php
php:
  - "7.3"
  - "7.4"
  - "8.0"

before_script:
  - phpenv config-add docker/php/xdebug.ini
  - composer selfupdate
  - composer install --prefer-source

script:
  - vendor/bin/phpunit
